workflows:
  ios-release-workflow:
    name: iOS Release Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: "THAI STAT Admin_CI"
    environment:
      flutter: 3.16.2
      xcode: latest
    scripts:
      - name: Set up code signing
        script: | 
          keychain initialize
          # ดึงโปรไฟล์ "สีเขียว" จากหน้าเว็บมาลงเครื่อง
          xcode-project use-profiles
          
          # บังคับโปรเจกต์ให้เป็น Manual เพื่อให้เราคุมเองได้ 100%
          sed -i '' 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/g' ios/Runner.xcodeproj/project.pbxproj
          sed -i '' 's/DEVELOPMENT_TEAM = .*;/DEVELOPMENT_TEAM = HTYHCF93L8;/g' ios/Runner.xcodeproj/project.pbxproj
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build and Sign IPA
        script: |
          # 1. รัน Flutter Build เพื่อรัน Pods และเตรียมเครื่องยนต์ให้พร้อม
          flutter build ios --release --no-codesign
          
          # 2. ใช้คำสั่งวิเศษเพื่อ Build IPA โดย "ข้าม" การตรวจใบรับรองในขั้นตอนแรก (Archive)
          # แล้วค่อยให้มันไปเซ็นชื่อจริงๆ ในขั้นตอนสุดท้าย (Export)
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner \
            --archive-flags="CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
