workflows:
  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    integrations:
      app_store_connect: "THAI STAT App Manager" # เปลี่ยนเป็นชื่อที่คุณตั้งในหน้า Integrations
    environment:
      flutter: stable
      xcode: latest
      groups:
        - apple_auth
    scripts:
      - name: Set up code signing settings on Codemagic
        script: | 
          keychain initialize
          # ดึงทั้ง Development และ App Store profiles เพื่อป้องกัน Xcode ถามหา
          app-store-connect fetch-signing-files "th.go.nso.ThaiStatNso2019" --type IOS_APP_DEVELOPMENT --create
          app-store-connect fetch-signing-files "th.go.nso.ThaiStatNso2019" --type IOS_APP_STORE --create
          keychain add-certificates
          # บังคับปิด Automatic Signing ในไฟล์โปรเจกต์
          sed -i '' 's/ProvisioningStyle = Automatic;/ProvisioningStyle = Manual;/g' ios/Runner.xcodeproj/project.pbxproj
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter build xcarchive
        script: |
          # Build โดยไม่เซ็นชื่อก่อน เพื่อสร้าง Archive
          flutter build ipa --release --no-codesign
      - name: Xcode build ipa (Sign with Codemagic)
        script: |
          # ใช้ Codemagic Tools เซ็นชื่อให้ตาม Profiles ที่ดึงมา
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner \
            --bundle-id "th.go.nso.ThaiStatNso2019"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
