workflows:
  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    integrations:
      app_store_connect: "THAI STAT Admin_CI" # เปลี่ยนเป็นชื่อที่คุณตั้งในหน้า Integrations
    environment:
      flutter: 3.16.2
      xcode: latest
      groups:
        - apple_auth
    scripts:
      - name: Set up code signing settings on Codemagic
        script: | 
          keychain initialize
          app-store-connect fetch-signing-files "th.go.nso.ThaiStatNso2019" --type IOS_APP_STORE --create
          keychain add-certificates
          # บังคับเปลี่ยนเป็น Manual Signing เพื่อไม่ให้ Xcode ถามหา Apple ID บัญชีบุคคล
          sed -i '' 's/CODE_SIGN_STYLE = Automatic/CODE_SIGN_STYLE = Manual/g' ios/Runner.xcodeproj/project.pbxproj
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter build ipa
        script: |
          flutter build ipa --release --export-method app-store
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
